import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import { Inter } from "next/font/google";
import AppHeader from "../layout/app-header";
import AppFooter from "../layout/app-footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pixel Up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
